packageExtensions:
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"

  "ts-jest@*":
    dependencies:
      "jest-config": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-rc.js
